### PR TITLE
docs: stop using deprecated cdk method

### PR DESCRIPTION
**Pull request by codeandcats**
Was using `lambda.Code.asset` which is deprecated. Now uses `lambda.Code.fromAsset` (just like the video does).

### CODE REVIEW

**Comment by zacjones93** [comment]
@codeandcats Thanks for the PR! 

Can you add a note and link to the docs about the deprecated method underneath that codeblock? 

https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/lambda/Code.html#asset-java.lang.String-

**Comment by codeandcats** [comment]
Hi @zacjones93,

TBH I don't see any need to link to the docs on the deprecated method as after this PR there will be no mention of the deprecated method (the video actually uses the new method).

**Comment by zacjones93** [comment]
That's a fair point

**Comment by zacjones93** [comment]
@all-contributors please add @codeandcats for content

**Pull request merged**
